name: CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Fetch tags and master for GitVersion
      run: |
          git fetch --tags
          git branch --create-reflog master origin/master
    - name: Git Version
      uses: roryprimrose/rungitversion@v1.0.0
    - name: Output version values 
      run: |  
        echo "Major: ${{ steps.gitversion.outputs.Major }}"
        echo "Minor: ${{ steps.gitversion.outputs.Minor }}"
        echo "Patch: ${{ steps.gitversion.outputs.Patch }}"
    - name: Run Tests
      run: |
        dotnet test
    - uses: actions/setup-dotnet@v1.7.2
    - run: dotnet build .
    - name: Prepare Artifact
      run: |
        mkdir plugins
        mkdir plugins/R2API
        cp R2API/bin/Debug/**/*.dll plugins/R2API/
        cp R2API/bin/Debug/**/*.xml plugins/R2API/
    - name: Upload R2API Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: R2API
        path: |
          plugins/*
          manifest.json
          icon.png
          README.md
