name: CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Fetch tags and master for GitVersion
      run: |
          git fetch --tags
          git branch --create-reflog master origin/master
    - name: GitVersion
      id: gitversion
      uses: nmcc/actions/gitversion@v1
      with:
        path-to-gitversion: packages/GitVersion.CommandLine/tools/GitVersion.exe
    - name: Create Release
      uses: actions/create-release@v1
      with:
          tag_name: ${{ steps.gitversion.outputs.SemVer }}
    - name: Run Tests
      run: |
        dotnet test
    - uses: actions/setup-dotnet@v1.7.2
    - run: dotnet build .
    - name: Prepare Artifact
      run: |
        mkdir plugins
        mkdir plugins/R2API
        mkdir monomod
        cp R2API/bin/Debug/netstandard2.0/*.dll plugins/R2API/
        cp R2API/bin/Debug/netstandard2.0/*.xml plugins/R2API/
        cp R2API.MonoMod/bin/Debug/netstandard2.0/*.mm.dll monomod/
    - name: Upload R2API Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: R2API
        path: |
          plugins/*
          monomod/*
          manifest.json
          icon.png
          README.md
