name: NuGet Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
        
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.13
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        
    - name: Restore dependencies
      run: nuget restore R2API.sln
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Update versions
      run: |
        sed -i -E "s/(PluginVersion\s*=\s*)\"0.0.1\"/\1\"$GitVersion_MajorMinorPatch\"/" R2API/R2API.cs
        sed -i -E "s/(\"version_number\":\s*)\"0.0.1\"/\1\"$GitVersion_MajorMinorPatch\"/" manifest.json
        sed -i -E "s/(PluginVersion\s*=\s*)\"0.0.1\"/\1\"$GitVersion_MajorMinorPatch\"/" R2API.Test/R2APITest.cs
    - name: Build
      run: dotnet build --no-restore -p:Version=$GitVersion_MajorMinorPatch

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json'
